# Local environment configuration

# DataSource Configuration - H2 in-memory database
spring:
  datasource:
    url: jdbc:h2:mem:employeedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  # CORS configuration for local environment
  mvc:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: Authorization, Content-Type
      allow-credentials: true
      max-age: 3600

# Logging Configuration
logging:
  level:
    com.amaris.employee_management: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG

# Cache Configuration
cache:
  employees:
    max-size: 50
    expire-after-write-minutes: 120
    expire-after-access-minutes: 60

# External API Configuration
employee:
  api:
    url: https://dummy.restapiexample.com/api/v1