# Common configuration for all environments

spring:
  application:
    name: employee-management-service
  profiles:
    active: local
  
  # Common JPA settings
  jpa:
    open-in-view: false
  
  # Common Jackson settings
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  compression:
    request:
      enabled: true
    response:
      enabled: true

# Common Server Configuration
server:
  servlet:
    context-path: /api

# Common Management Endpoints
management:
  endpoint:
    health:
      enabled: true
  health:
    diskspace:
      enabled: true

# Employee API Configuration (default)
employee:
  api:
    url: https://dummy.restapiexample.com/api/v1