server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: employee-management
  profiles:
    active: dev

# External API configuration
api:
  external:
    base-url: http://dummy.restapiexample.com/api/v1/
    employees-endpoint: employees
    employee-by-id-endpoint: employee/{id}
    timeout: 5000
    retry:
      max-attempts: 3
      initial-backoff: 1000
      max-backoff: 5000
      multiplier: 2.0

# Cache configuration
cache:
  employees:
    max-size: 100
    expire-after-write-minutes: 60
    expire-after-access-minutes: 30

# Logging
logging:
  level:
    com.amaris.employee_management: INFO
    org.springframework.web: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG